name: MoVR
favicon: null
layout_spectrum: 0.91753
typography_spectrum: 0.58368
title: VR NEWS
description: FOR INTERESTED PEOPLE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#73603D'
    - '#BF8A49'
    - '#F2CA80'
    - '#5E5A59'
    - '#0D0D0D'
  brandStrength: 0.1875
  lightness: 1
  saturation: 0.3131175031885505
  rhythmicContrast: 0.75
purpose: []
